In [3]:
import numpy as np
import time 

In [62]:
test = np.arange(5)
test.shape


(5,)

In [ ]:
l = [1,2,3,4,5]

In [ ]:
np.array(l)

In [ ]:
size =1000000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)


In [ ]:
start = time.time()
result = [x+y for x,y in zip(l1,l2)]
print((time.time()- start) *1000)
#result

In [ ]:
start = time.time()
result1 = a1+a2
print((time.time()- start) *1000)


In [66]:
np_arr1 = np.array([1,2,3,4]) # This is a vector A 1D array is a vector; its shape is just the number of components
np_arr1.shape # hence will output (4,)
np_arr = np.array([(1,2,3), (4,5,6), (7,8,9)])
np_arr.ndim # find the dimensions 
np_arr.dtype # find the type of the object stored in array
#np_arr.itemsize # memory allocation of each element
#np_arr[1][2]
np_arr.shape , np_arr1.shape # number of rows,column ( 2,3) 2 rows and 3 columns 
#np_arr.size #total number of elements in the array

((3, 3), (4,))

In [71]:
#Slicing
#syntax arr[<from:to rows>, <columns to show>]
np_arr[:,(1,2)] # allrows column1

array([[2, 3],
       [5, 6],
       [8, 9]])

In [83]:
np1 = np.ones(6)
np1.shape




(6,)

In [88]:
np2= np.ones(5).reshape(5,1)
np2.size, np2.shape

(5, (5, 1))

In [86]:
np1+np2

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [1]:
np.genfromtxt('<filename>'') # this can read from csv file

SyntaxError: EOL while scanning string literal (<ipython-input-1-35c1c3d1736a>, line 1)

In [17]:
h1 = np.ones([2,4])
h2= np.zeros([2,2])

In [13]:
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
h2

array([[0., 0.],
       [0., 0.]])

In [16]:
np.vstack([h1,h2]) 

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [42]:
a1 = np.random.randint(10, size=(2, 4))

In [43]:
a1

array([[3, 9, 4, 0],
       [7, 9, 4, 8]])

In [52]:
np.all(a1 >5 )

False